language: ruby

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.3.2.mysql2
  - gemfiles/Gemfile.4.2.mysql2
  - gemfiles/Gemfile.4.2.pg
  - gemfiles/Gemfile.5.0.mysql2
  - gemfiles/Gemfile.5.0.pg

before_script:
  - psql -c 'create database minidusen_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS minidusen_test;'

script: bundle exec rspec spec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de

branches:
  only:
    - master

matrix:
  include:
    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.3.2.mysql2

    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.4.2.mysql2

    - rvm: 2.1.8
      gemfile: gemfiles/Gemfile.4.2.pg

    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.4.2.mysql2

    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile.4.2.pg

    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.5.0.mysql2

    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.5.0.pg
